### ISSUE TITLE
ESA journals (Wiley) & other Wiley journals are implemented separately. Why?

### ISSUE THREAD

**Issue by rossmounce** [ropensci/suppdata#16]
Much as I strongly dislike that they moved to Wiley, I must note that Ecological Society of America (ESA) journals, including all backfile content are all available on the Wiley platform.

Why then have both `.suppdata.wiley` and `.suppdata.esa_archives` ?

The ESA method looks harder to use because you have to specify the exact file name which isn't necessarily predictive from just the article DOI e.g. "S1_data.csv" , so I would dump the ESA specific methods unless you can justify a reason I'm not aware of.

I also note from http://esapubs.org/archive/ that Ecological Archives doesnt look like a safe bet in the long term. It's been wound down already and will it still be there in 5 years time...?
```
"Ecological Archives through the end of 2015 will be hosted on FigShare once the transition to publishing with Wiley is completed. Thereafter, supplemental material may be hosted on Wiley Online, and/or data deposited with FigShare, Dryad, and other repositories"
```

**Comment by willpearse** [comment]
When `suppdata` was first written, ESA journals weren't on Wiley, and so this wasn't possibile. Now it's possible to load them from Wiley (as you describe) and from their original 'home' on the ESA website. Since I have users who are using the older ESA code, and those functions don't 'compete' with the Wiley code as Wiley have given everything proper DOIs, I'm going to leave everything as is for backwards-compatibility.
